// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/person.proto

package personpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_person_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_proto_person_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_proto_person_proto_rawDescGZIP(), []int{0}
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Patronymic    *string                `protobuf:"bytes,4,opt,name=patronymic,proto3,oneof" json:"patronymic,omitempty"`
	Age           uint32                 `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Gender        Gender                 `protobuf:"varint,6,opt,name=gender,proto3,enum=person.Gender" json:"gender,omitempty"`
	Nationality   string                 `protobuf:"bytes,7,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Emails        []string               `protobuf:"bytes,8,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_proto_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_proto_person_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Person) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Person) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Person) GetPatronymic() string {
	if x != nil && x.Patronymic != nil {
		return *x.Patronymic
	}
	return ""
}

func (x *Person) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *Person) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *Person) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

type CreatePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Patronymic    *string                `protobuf:"bytes,3,opt,name=patronymic,proto3,oneof" json:"patronymic,omitempty"`
	Emails        []string               `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonRequest) Reset() {
	*x = CreatePersonRequest{}
	mi := &file_proto_person_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonRequest) ProtoMessage() {}

func (x *CreatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_person_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePersonRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreatePersonRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreatePersonRequest) GetPatronymic() string {
	if x != nil && x.Patronymic != nil {
		return *x.Patronymic
	}
	return ""
}

func (x *CreatePersonRequest) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

type GetPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonRequest) Reset() {
	*x = GetPersonRequest{}
	mi := &file_proto_person_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonRequest) ProtoMessage() {}

func (x *GetPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonRequest.ProtoReflect.Descriptor instead.
func (*GetPersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_person_proto_rawDescGZIP(), []int{2}
}

func (x *GetPersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPersonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonsRequest) Reset() {
	*x = ListPersonsRequest{}
	mi := &file_proto_person_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonsRequest) ProtoMessage() {}

func (x *ListPersonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonsRequest.ProtoReflect.Descriptor instead.
func (*ListPersonsRequest) Descriptor() ([]byte, []int) {
	return file_proto_person_proto_rawDescGZIP(), []int{3}
}

func (x *ListPersonsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPersonsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListPersonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Person              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonsResponse) Reset() {
	*x = ListPersonsResponse{}
	mi := &file_proto_person_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonsResponse) ProtoMessage() {}

func (x *ListPersonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonsResponse.ProtoReflect.Descriptor instead.
func (*ListPersonsResponse) Descriptor() ([]byte, []int) {
	return file_proto_person_proto_rawDescGZIP(), []int{4}
}

func (x *ListPersonsResponse) GetData() []*Person {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPersonsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPersonsResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPersonsResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Emails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emails) Reset() {
	*x = Emails{}
	mi := &file_proto_person_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emails) ProtoMessage() {}

func (x *Emails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emails.ProtoReflect.Descriptor instead.
func (*Emails) Descriptor() ([]byte, []int) {
	return file_proto_person_proto_rawDescGZIP(), []int{5}
}

func (x *Emails) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type UpdatePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     *string                `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Patronymic    *string                `protobuf:"bytes,4,opt,name=patronymic,proto3,oneof" json:"patronymic,omitempty"`
	Age           *uint32                `protobuf:"varint,5,opt,name=age,proto3,oneof" json:"age,omitempty"`
	Gender        *Gender                `protobuf:"varint,6,opt,name=gender,proto3,enum=person.Gender,oneof" json:"gender,omitempty"`
	Nationality   *string                `protobuf:"bytes,7,opt,name=nationality,proto3,oneof" json:"nationality,omitempty"`
	Emails        *Emails                `protobuf:"bytes,8,opt,name=emails,proto3,oneof" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonRequest) Reset() {
	*x = UpdatePersonRequest{}
	mi := &file_proto_person_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonRequest) ProtoMessage() {}

func (x *UpdatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_person_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePersonRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdatePersonRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdatePersonRequest) GetPatronymic() string {
	if x != nil && x.Patronymic != nil {
		return *x.Patronymic
	}
	return ""
}

func (x *UpdatePersonRequest) GetAge() uint32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *UpdatePersonRequest) GetGender() Gender {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *UpdatePersonRequest) GetNationality() string {
	if x != nil && x.Nationality != nil {
		return *x.Nationality
	}
	return ""
}

func (x *UpdatePersonRequest) GetEmails() *Emails {
	if x != nil {
		return x.Emails
	}
	return nil
}

type DeletePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonRequest) Reset() {
	*x = DeletePersonRequest{}
	mi := &file_proto_person_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonRequest) ProtoMessage() {}

func (x *DeletePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonRequest.ProtoReflect.Descriptor instead.
func (*DeletePersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_person_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonResponse) Reset() {
	*x = DeletePersonResponse{}
	mi := &file_proto_person_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonResponse) ProtoMessage() {}

func (x *DeletePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonResponse.ProtoReflect.Descriptor instead.
func (*DeletePersonResponse) Descriptor() ([]byte, []int) {
	return file_proto_person_proto_rawDescGZIP(), []int{8}
}

var File_proto_person_proto protoreflect.FileDescriptor

const file_proto_person_proto_rawDesc = "" +
	"\n" +
	"\x12proto/person.proto\x12\x06person\"\xfc\x01\n" +
	"\x06Person\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12#\n" +
	"\n" +
	"patronymic\x18\x04 \x01(\tH\x00R\n" +
	"patronymic\x88\x01\x01\x12\x10\n" +
	"\x03age\x18\x05 \x01(\rR\x03age\x12&\n" +
	"\x06gender\x18\x06 \x01(\x0e2\x0e.person.GenderR\x06gender\x12 \n" +
	"\vnationality\x18\a \x01(\tR\vnationality\x12\x16\n" +
	"\x06emails\x18\b \x03(\tR\x06emailsB\r\n" +
	"\v_patronymic\"\x9d\x01\n" +
	"\x13CreatePersonRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12#\n" +
	"\n" +
	"patronymic\x18\x03 \x01(\tH\x00R\n" +
	"patronymic\x88\x01\x01\x12\x16\n" +
	"\x06emails\x18\x04 \x03(\tR\x06emailsB\r\n" +
	"\v_patronymic\"\"\n" +
	"\x10GetPersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x12ListPersonsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"y\n" +
	"\x13ListPersonsResponse\x12\"\n" +
	"\x04data\x18\x01 \x03(\v2\x0e.person.PersonR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\" \n" +
	"\x06Emails\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x82\x03\n" +
	"\x13UpdatePersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x01R\blastName\x88\x01\x01\x12#\n" +
	"\n" +
	"patronymic\x18\x04 \x01(\tH\x02R\n" +
	"patronymic\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\x05 \x01(\rH\x03R\x03age\x88\x01\x01\x12+\n" +
	"\x06gender\x18\x06 \x01(\x0e2\x0e.person.GenderH\x04R\x06gender\x88\x01\x01\x12%\n" +
	"\vnationality\x18\a \x01(\tH\x05R\vnationality\x88\x01\x01\x12+\n" +
	"\x06emails\x18\b \x01(\v2\x0e.person.EmailsH\x06R\x06emails\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\r\n" +
	"\v_patronymicB\x06\n" +
	"\x04_ageB\t\n" +
	"\a_genderB\x0e\n" +
	"\f_nationalityB\t\n" +
	"\a_emails\"%\n" +
	"\x13DeletePersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeletePersonResponse*D\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x022\xd3\x02\n" +
	"\rPersonService\x12;\n" +
	"\fCreatePerson\x12\x1b.person.CreatePersonRequest\x1a\x0e.person.Person\x125\n" +
	"\tGetPerson\x12\x18.person.GetPersonRequest\x1a\x0e.person.Person\x12F\n" +
	"\vListPersons\x12\x1a.person.ListPersonsRequest\x1a\x1b.person.ListPersonsResponse\x12;\n" +
	"\fUpdatePerson\x12\x1b.person.UpdatePersonRequest\x1a\x0e.person.Person\x12I\n" +
	"\fDeletePerson\x12\x1b.person.DeletePersonRequest\x1a\x1c.person.DeletePersonResponseB\x17Z\x15pkg/personpb;personpbb\x06proto3"

var (
	file_proto_person_proto_rawDescOnce sync.Once
	file_proto_person_proto_rawDescData []byte
)

func file_proto_person_proto_rawDescGZIP() []byte {
	file_proto_person_proto_rawDescOnce.Do(func() {
		file_proto_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_person_proto_rawDesc), len(file_proto_person_proto_rawDesc)))
	})
	return file_proto_person_proto_rawDescData
}

var file_proto_person_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_person_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_person_proto_goTypes = []any{
	(Gender)(0),                  // 0: person.Gender
	(*Person)(nil),               // 1: person.Person
	(*CreatePersonRequest)(nil),  // 2: person.CreatePersonRequest
	(*GetPersonRequest)(nil),     // 3: person.GetPersonRequest
	(*ListPersonsRequest)(nil),   // 4: person.ListPersonsRequest
	(*ListPersonsResponse)(nil),  // 5: person.ListPersonsResponse
	(*Emails)(nil),               // 6: person.Emails
	(*UpdatePersonRequest)(nil),  // 7: person.UpdatePersonRequest
	(*DeletePersonRequest)(nil),  // 8: person.DeletePersonRequest
	(*DeletePersonResponse)(nil), // 9: person.DeletePersonResponse
}
var file_proto_person_proto_depIdxs = []int32{
	0, // 0: person.Person.gender:type_name -> person.Gender
	1, // 1: person.ListPersonsResponse.data:type_name -> person.Person
	0, // 2: person.UpdatePersonRequest.gender:type_name -> person.Gender
	6, // 3: person.UpdatePersonRequest.emails:type_name -> person.Emails
	2, // 4: person.PersonService.CreatePerson:input_type -> person.CreatePersonRequest
	3, // 5: person.PersonService.GetPerson:input_type -> person.GetPersonRequest
	4, // 6: person.PersonService.ListPersons:input_type -> person.ListPersonsRequest
	7, // 7: person.PersonService.UpdatePerson:input_type -> person.UpdatePersonRequest
	8, // 8: person.PersonService.DeletePerson:input_type -> person.DeletePersonRequest
	1, // 9: person.PersonService.CreatePerson:output_type -> person.Person
	1, // 10: person.PersonService.GetPerson:output_type -> person.Person
	5, // 11: person.PersonService.ListPersons:output_type -> person.ListPersonsResponse
	1, // 12: person.PersonService.UpdatePerson:output_type -> person.Person
	9, // 13: person.PersonService.DeletePerson:output_type -> person.DeletePersonResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_person_proto_init() }
func file_proto_person_proto_init() {
	if File_proto_person_proto != nil {
		return
	}
	file_proto_person_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_person_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_person_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_person_proto_rawDesc), len(file_proto_person_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_person_proto_goTypes,
		DependencyIndexes: file_proto_person_proto_depIdxs,
		EnumInfos:         file_proto_person_proto_enumTypes,
		MessageInfos:      file_proto_person_proto_msgTypes,
	}.Build()
	File_proto_person_proto = out.File
	file_proto_person_proto_goTypes = nil
	file_proto_person_proto_depIdxs = nil
}
